/*
{
	"Code": "MTM4S/S2AKPIM/1",
	"Single Module Frame": "System 200 Audio - 1 button",
	"Finish": "Standard",
	"Module Size": 4,
	"Mount": "Surface mount",
	"System": "System 200",
	"A/V": "Audio",
	"Keypad": "Keypad",
	"Proximity": "Proximity",
	"Info Module": "Info Module",
	"Hearing Module": "",
	"Digital Display": "",
	"moduli aggiuntivi": "Keypad,Proximity,Info Module,",
	"Buttons": 1,
	"Divided": "",
	"Mounting": "MTMSP4M",
	"Flush Rainshield": "",
	"Frame": "MTMTP4M",
	"Electronics Module 1": "MTMA/200",
	"Front Piece 1": "MTMFAL1P",
	"Electronics Module 2": "MTMNA",
	"Front Piece 2": "MTMFNA",
	"Electronics Module 3": "MTMRFID",
	"Front Piece 3": "MTMFRFID",
	"Electronics Module 4": "MTMMI",
	"Front Piece 4": "MTMFMI",
	"CI": 10,
	"Description": "MTM System 200 Audio Surface mount with 1 button; inc: Keypad / Proximity / Info Module /  /"
}
*/
